# 데이터 분석 - Pandas 기초 실습

**주제**
- Pandas 라이브러리
- 데이터프레임과 시리즈
- 데이터 살펴보기
- 데이터 변환하기
- 데이터 요약하기
---

## 숫자세기

medical.csv에는 성인 1만명의 건강검진 데이터이며 데이터는 다음과 같이 구성되어 있습니다.
```
컬럼 명	데이터 소개
BTH_G	연령(그룹)
SBP	수축기 혈압
DBP	연령(그룹)
FBS	공복 혈당
SEX	성별
DIS	고혈압/당뇨병 진료 여부
BMI     체질량 지수
```	

데이터셋을 읽고, 아래 지시사항을 따르세요.

1. 데이터프레임 df의 SEX 컬럼에 숫자로 된 데이터를 변환합니다.
- 1 → 남성
- 2 → 여성

2. 데이터프레임 df의 DIS 컬럼에 숫자로 된 데이터를 변환합니다. 
- 1 → 고혈압/당뇨병 진료내역 있음
- 2 → 고혈압 진료내역 있음
- 3 → 당뇨병 진료내역 있음
- 4 → 고혈압/당뇨병 진료내역 없음
3. 데이터프레임 df의 DIS 컬럼에 들어있는 각 값들이 몇 개씩 저장되어 있는지 출력합니다.

In [14]:
import pandas as pd 

df1 = pd.read_csv('data/medical.csv') 

df1.head()

   Unnamed: 0  SEX  BTH_G  SBP  DBP  FBS  DIS   BMI
0           0    2      6  102   72   86    4  19.2
1           1    2     27  106   64   99    4  26.2
2           2    2     13  108   61   90    4  22.9
3           3    2     18  110   67   90    4  24.5
4           4    2     18  124   80   86    4  26.2

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10000 non-null  int64
 1   SEX         10000 non-null  int64
 2   BTH_G       10000 non-null  int64
 3   SBP         10000 non-null  int64
 4   DBP         10000 non-null  int64
 5   FBS         10000 non-null  int64
 6   DIS         10000 non-null  int64
 7   BMI         10000 non-null  float64
dtypes: float64(1), int64(7)
memory usage: 625.1 KB

In [16]:
# 1. 성별 숫자값을 반환하기 
sex_number = {2 : "여성", 1 : "남성"}


df1['SEX'] = df1['SEX'].map(sex_number)

In [17]:
# 2.  데이터프레임 df의 DIS 컬럼에 숫자로 된 데이터를 변환
dis_map = {1 : "고혈압/당뇨병 진료내역 있음" ,
           2 : "고혈압 진료내역 있음" ,
           3 : "당뇨병 진료내역 있음" , 
           4 : "고혈압/당뇨병 진료내역 없음" }

df1['DIS'] = df1['DIS'].map(dis_map)

In [18]:
df1.rename(columns={'Unnamed: 0': 'ID'}, inplace=True)

In [19]:
# 3. 데이터프레임 df의 DIS 컬럼에 들어있는 각 값들이 몇 개씩 저장되어 있는지 출력합니다.

df1.groupby("DIS")['ID'].count()

DIS
고혈압 진료내역 있음        1684
고혈압/당뇨병 진료내역 없음    7330
고혈압/당뇨병 진료내역 있음     538
당뇨병 진료내역 있음         448
Name: ID, dtype: int64

## 콤마가 있는 숫자 처리하기

access_data.csv 에는 한 홈페이지의 접속경로 통계 데이터가 저장되어 있습니다.

```
컬럼 명	데이터 소개	데이터 유형
접속일자	접속한 날짜	object
PC접속수	PC를 통해 홈페이지에 접속한 수	object
모바일접속수	모바일을 통해 홈페이지에 접속한 수	object
```

데이터를 읽고, 아래 지시사항을 따르세요.

1. df(데이터프레임)의 '접속일자' 컬럼의 자료형을 datetime으로 변경합니다.
2. del_comma() 함수를 완성하여 'PC접속수' 와 '모바일접속수' 컬럼의 콤마를 제거합니다. (문자열의 replace를 활용)
  - 매개변수로 받은 문자열에 콤마(,)가 있다면 제거
3. 콤마를 지운 'PC접속수' 와 '모바일접속수' 컬럼의 자료형을 숫자형 자료형(int)으로 변경합니다.
4. df의 'PC접속수' 컬럼과 '모바일접속수' 컬럼을 이용해서 df에 '전체접속수' 컬럼을 추가합니다.

In [ ]:
# 함수를 완성하세요.
def del_comma(data):
    if data in ',':
        pass
    return data

In [14]:
df2 = pd.read_csv("data/access_data.csv")

df2.info()
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   접속일자    365 non-null    object
 1   PC접속수   365 non-null    object
 2   모바일접속수  365 non-null    object
dtypes: object(3)
memory usage: 8.7+ KB

         접속일자  PC접속수 모바일접속수
0  2021-01-01  1,870    900
1  2021-01-02  1,660  1,280
2  2021-01-03  4,440    550
3  2021-01-04  2,890    520
4  2021-01-05  2,500    400

In [15]:
# 1. df(데이터프레임)의 '접속일자' 컬럼의 자료형을 datetime으로 변경합니다.
df2['접속일자'] = pd.to_datetime(df2['접속일자'])

## 서울시 인구수 기반 고령화 정도 분석

seoul_population.csv 파일에 2023년 서울시 지역구별 인구수 데이터가 저장되어 있습니다.

데이터를 읽고 아래 지시사항을 따르세요.

1. 데이터프레임 df에 "노인인구비율" 컬럼을 생성하여 지역구별로 총인구수 대비 노인인구의 비율을 저장합니다. (70대 이상의 인구를 노인 인구라고 가정합니다)
2. 데이터프레임 df에 "고령여부" 컬럼을 생성하고 "노인인구비율" 컬럼값이 0.14 이상이면 O (대문자 o), 0.14 미만이면 X (대문자 x)를 저장합니다.
3. 최종 완성된 데이터프레임을 출력합니다.

In [21]:
df = pd.read_csv("data\seoul_population.csv")

# 고령여부에 사용할 조건 함수 생성 
def senior(p) : 
    if p >= 0.14 :
        return 'O'
    else :
        return 'X'

# 컬럼 생성 
df["노인인구비율"] = (df['70대']+df['80대']+df['90대 이상'])/df['총인구수']
df["고령여부"] = df["노인인구비율"].apply(senior)

df

,동별,10대 미만,10대,20대,30대,40대,50대,60대,70대,80대,90대 이상,총인구수,노인인구비율,고령여부
0,종로구,6559,10735,27787,21014,20982,25061,20952,11556,6600,966,152212,0.125627,X
1,중구,6313,6909,21404,22120,18283,20648,18898,10432,5504,879,131390,0.127978,X
2,용산구,12886,15451,33676,41419,35389,37195,30318,15744,8987,1417,232482,0.112473,X
3,성동구,17968,18917,45156,46557,42643,45743,38809,20199,9980,1268,287240,0.109480,X
4,광진구,16678,25060,66308,56979,50188,54710,46016,22985,10650,1351,350925,0.099697,X
5,동대문구,18664,23627,68182,50800,49232,52729,48409,27928,13677,1636,354884,0.121845,X
6,중랑구,20413,24947,52889,58911,55251,66189,62900,32317,14329,1782,389928,0.124197,X
7,성북구,25675,36931,72533,58952,66307,71106,58046,33165,16941,2199,441855,0.118376,X
8,강북구,12711,20072,41073,36571,42058,51196,47893,29468,14314,1578,296934,0.152761,O
9,도봉구,15222,23320,39585,38690,44264,54841,52608,28344,14116,1868,312858,0.141687,O
10,노원구,27828,49251,69731,62325,78161,86441,72611,38672,19146,2823,506989,0.119610,X
11,은평구,25273,36258,63301,66558,71870,77266,68067,38852,19160,2161,468766,0.128365,X
12,서대문구,18693,23338,56980,46778,46301,49864,41610,23574,13142,1686,321966,0.119273,X
13,마포구,21818,27785,65115,65671,59271,56307,42506,23574,12732,1763,376542,0.101102,X
14,양천구,26670,48378,54432,54500,74396,75687,62561,31263,12549,1909,442345,0.103360,X
15,강서구,33202,42989,82622,98837,88817,84234,80793,42127,17378,2712,573711,0.108447,X
16,구로구,25161,29399,53834,65422,63868,68459,62327,33802,13994,1717,417983,0.118457,X
17,금천구,11307,13774,36851,39940,32662,42120,37953,18841,8047,972,242467,0.114902,X
18,영등포구,24386,24286,59813,73779,58765,62021,52809,28035,13366,1739,398999,0.108121,X
19,동작구,21226,27047,68889,61141,56580,58456,51277,30025,13855,1881,390377,0.117223,X
20,관악구,18135,26935,115634,90786,64915,68572,62020,37371,16465,1795,502628,0.110680,X
21,서초구,28842,44949,50666,57681,73710,64198,47910,27945,11296,1782,408979,0.100306,X
22,강남구,32605,60648,69134,77917,98019,84103,61734,37203,14124,2330,537817,0.099768,X
23,송파구,45614,58265,87627,106721,108477,102607,89995,44951,16719,2728,663704,0.097028,X
24,강동구,32305,39306,58094,69934,75608,71427,68523,34240,12644,1946,464027,0.105231,X

## 당뇨 데이터 변환

diabetes.csv에는 환자에 대한 당뇨병 데이터가 저장되어 있습니다.
```
컬럼	의미	설명
Pregnancies	임신 횟수	정수형
Glucose	포도당 부하검사 수치	정수형
BloodPressure	혈압	정수형
SkinThickness	팔 삼두근 뒤쪽의 피하지방 측정값	정수형
Insulin	혈청 인슐린	정수형
BMI	체질량 지수	실수형
DiabetesPedigreeFunction	당뇨 내력 가중치 값	실수형
Age	나이	정수형
Outcome	당뇨여부	1(Yes), 0(No)
```

1. categorize_bmi(bmi) : 비만도 분류하기
bmi에 따른 비만도를 분류합니다.
아래 조건에 맞는 레이블을 return 할 수 있도록 categorize_bmi를 작성합니다.
```
범위	            분류	    레이블
18.5 이하	        저체중	   0
18.5 초과 23.0 이하	 정상	   1
23.0 초과 25.0 이하	 과체중	    2
25.0 초과	        비만	  3
```

2. bmi_to_categorical(data) : 데이터 변환하기
데이터프레임의 BMI 컬럼 데이터를 매개변수로 받아 연속형 데이터를 범주형 데이터(0~3)의 레이블을 가지도록 변환하는 함수를 작성합니다.

In [4]:
import pandas as pd 

def categorize_bmi(bmi: str) -> int:  
    """비만도를 분류하는 함수입니다."""
    if bmi <= 18.5 :  
        return 0
    elif bmi <= 23 :  
        return 1  
    elif bmi <= 25 :  
        return 2  
    else:  
        return 3

def bmi_to_categorical(data):
    new_series = df['BMI'].apply(categorize_bmi)
    return new_series

# 데이터를 읽어오세요!
df = pd.read_csv('data\diabetes.csv')

# df의 BMI Column을 범주형 데이터로 변환하여 저장합니다.
df["BMI"] = bmi_to_categorical(df["BMI"])

# BMI 컬럼을 출력하세요.
print(df['BMI'])

0      3
1      3
2      3
3      3
4      3
      ..
387    3
388    3
389    3
390    3
391    3
Name: BMI, Length: 392, dtype: int64

## 그룹으로 묶기
아래와 같은 학생들의 성적을 나타낸 데이터 프레임이 주어집니다. 아래 지시사항을 따르세요.

```
인덱스	반	국어성적	수학성적
0	A	100	85
1	B	96	88
2	C	94	91
3	A	92	94
4	B	90	97
5	C	86	100
```

1. 반별 국어성적의 합, 수학성적의 합, 반별 국어성적의 평균, 수학성적의 평균
2. 위 4개의 값을 구하고 출력합니다.

In [5]:
df = pd.DataFrame(
        {
            "class": ["A", "B", "C", "A", "B", "C"],
            "Korean": [100, 96, 94, 92, 90, 86],
            "Math": [85, 88, 91, 94, 97, 100],
        }
    )

In [10]:
print("==== 반별 국어점수의 합 ====")
print(df.groupby('class')['Korean'].sum())
print("==== 반별 수학점수의 합 ====")
print(df.groupby('class')['Math'].sum())
print("==== 반별 국어점수의 평균 ====")
print(df.groupby('class')['Korean'].mean())
print("==== 반별 수학점수의 평균 ====")
print(df.groupby('class')['Math'].mean())

==== 반별 국어점수의 합 ====
class
A    192
B    186
C    180
Name: Korean, dtype: int64
==== 반별 수학점수의 합 ====
class
A    179
B    185
C    191
Name: Math, dtype: int64
==== 반별 국어점수의 평균 ====
class
A    96.0
B    93.0
C    90.0
Name: Korean, dtype: float64
==== 반별 수학점수의 평균 ====
class
A    89.5
B    92.5
C    95.5
Name: Math, dtype: float64

## 펭귄 데이터 그룹화하기
데이터의 구조는 아래와 같습니다. 아래 데이터를 바탕으로 아래 지시사항을 따르세요.
```
컬럼 명	형식	내용
species	object	펭귄의 종
island	object	펭귄이 관찰된 섬의 이름
bill_length_mm	float64	펭귄 부리의 길이
bill_depth_mm	float64	펭귄 부리의 깊이
flipper_length_mm	float64	펭귄의 지느러미 길이
body_mass_g	float64	펭귄의 체중
sex	object	펭귄의 성별
```

1. penguins.csv 파일을 읽어옵니다.
2. 첫번째 줄에 그룹화할 기준의 컬럼명을 입력받습니다.
  - 그룹화할 컬럼은 최소 한 개에서 최대 두 개까지 입력받습니다.
  - 입력하는 컬럼은 , 로 구분됩니다.
3. 첫 번째 줄에 입력받은 컬럼 명을 기준으로 순서대로 그룹화한 후, 평균을 구하여 출력합니다.
숫자형 자료에 대해서만 출력합니다.
(mean 메서드 사용시 numeric_only 인자에 True를 전달하면 숫자형 자료에 대해서만 출력할 수 있습니다.)

입력 예시 1
```
island
```

출력 예시 1
```
           bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
island                                                                  
Biscoe          44.300000      15.854839         207.709677  4671.774194
Dream           43.762500      18.459375         192.437500  3599.218750
Torgersen       39.133333      17.883333         187.500000  3716.666667
```

입력 예시 2
```
species,island
```

출력 예시 2
```
                     bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
species   island                                                                  
Adelie    Biscoe          38.800000      18.255556         188.333333  3627.777778
          Dream           37.520000      18.320000         188.733333  3486.666667
          Torgersen       39.133333      17.883333         187.500000  3716.666667
Chinstrap Dream           49.270588      18.582353         195.705882  3698.529412
Gentoo    Biscoe          46.550000      14.872727         215.636364  5098.863636
```

In [ ]:


# 펭귄 데이터 입력받기 
penguin = pd.read_csv("data\penguins.csv")

penguin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            70 non-null     object
 1   island             70 non-null     object
 2   bill_length_mm     69 non-null     float64
 3   bill_depth_mm      69 non-null     float64
 4   flipper_length_mm  69 non-null     float64
 5   body_mass_g        69 non-null     float64
 6   sex                66 non-null     object
dtypes: float64(4), object(3)
memory usage: 4.0+ KB

In [22]:
import pandas as pd 

# 그룹화 할 컬럼 받아내기 (최대 2개)
# * 1개인 경우 2개인 경우 분류 
group= input().split(",")

if len(group) <=2 :
   print(penguin.groupby(group).mean(numeric_only=True))
    
else :
    print("그룹화할 컬럼은 최소 한 개에서 최대 두 개까지 입력받습니다.")

           bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
island
Biscoe          44.300000      15.854839         207.709677  4671.774194
Dream           43.762500      18.459375         192.437500  3599.218750
Torgersen       39.133333      17.883333         187.500000  3716.666667

## 인도 IT 시장 점유율 확인하기
인도에서 스마트폰, 데스크탑, 태블릿PC 점유율을 기록한 csv 파일을 이용하여 csv 파일을 기준에 따라 그룹화하고 특정 인덱스의 최댓값을 구하려고 합니다. 파일 내의 컬럼에 대한 설명은 다음과 같습니다.
```
컬럼 명	형식	내용
Date	object	측정 날짜
Mobile	float64	모바일 시장 점유율
Desktop	float64	데스크탑 시장 점유율
Tablet	float64	태블릿PC 시장 점유율
```
1. india_shares.csv 파일을 읽어옵니다.
2. Date 컬럼을 활용해서 연, 월 데이터를 아래의 컬럼을 만들어서 저장하세요.
  - Year : Date 컬럼의 연에 해당하는 데이터
  - Month : Date 컬럼의 월에 해당하는 데이터
3. 그룹화할 기준의 컬럼 명 하나를 입력받습니다.
4. 불러온 csv 파일을 이용하여 입력받은 컬럼 명을 기준으로 순서대로 그룹화한 후, 평균을 구하여 출력합니다.
5. 숫자형 자료에 대해서만 출력합니다. 
(mean 메서드 사용시 numeric_only 인자에 True를 전달하면 숫자형 자료에 대해서만 출력할 수 있습니다.)

입력 예시
```
Month
```

출력 예시
```
          Mobile    Desktop    Tablet  Year
Month                                      
1      57.332667  42.156667  0.510000  2016
2      56.698000  42.801333  0.501333  2016
3      57.479333  42.007333  0.512667  2016
4      58.248667  41.222000  0.530667  2016
5      58.652667  40.799333  0.546667  2016
6      58.950000  40.497333  0.552000  2016
7      58.965333  40.487333  0.547333  2016
8      59.707333  39.724000  0.567333  2016
9      60.142667  39.306667  0.550667  2016
10     60.892000  38.572667  0.534000  2016
11     61.545333  37.924667  0.530000  2016
12     62.525333  36.951333  0.524667  2016
```

In [11]:
df = pd.read_csv('data\india_shares.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     180 non-null    object
 1   Mobile   180 non-null    float64
 2   Desktop  180 non-null    float64
 3   Tablet   180 non-null    float64
dtypes: float64(3), object(1)
memory usage: 5.8+ KB

In [13]:
df['Year'] = pd.to_datetime(df['Date']).dt.year
df['Month'] = pd.to_datetime(df['Date']).dt.month

group = input()

df.groupby(group).mean(numeric_only=True)

          Mobile    Desktop    Tablet    Year
Month
1      57.332667  42.156667  0.510000  2016.0
2      56.698000  42.801333  0.501333  2016.0
3      57.479333  42.007333  0.512667  2016.0
4      58.248667  41.222000  0.530667  2016.0
5      58.652667  40.799333  0.546667  2016.0
6      58.950000  40.497333  0.552000  2016.0
7      58.965333  40.487333  0.547333  2016.0
8      59.707333  39.724000  0.567333  2016.0
9      60.142667  39.306667  0.550667  2016.0
10     60.892000  38.572667  0.534000  2016.0
11     61.545333  37.924667  0.530000  2016.0
12     62.525333  36.951333  0.524667  2016.0